[book]
authors = ["Blockchain Scalability Book Contributors"]
language = "en"
multilingual = false
src = "."
title = "Blockchain Scalability Book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/neilydhan/Blockchain-Scalability-Book"
edit-url-template = "https://github.com/neilydhan/Blockchain-Scalability-Book/edit/main/{path}"
print = { enable = true }

[build]
build-dir = "book"

[watch]
ignore = ["*.git/*", "book/*"]
debounce = 1000

# Comment out or remove the [output.pdf] section during development
# Uncomment when you want to generate PDF
[output.pdf]
enable = true
renderer = ["html", "pdf"]
# command = "mdbook-pdf"
margin-left = 1.5
margin-right = 1.5
margin-top = 1.5
margin-bottom = 1.5
page-break = true
display-header = true
display-footer = true
scale = 1.0
prefer-local-renderer = true