[book]
authors = ["Neil Han"]
language = "en"
src = "."
title = "Blockchain Scalability Book"

[output.html]
additional-css = ["theme/print.css"]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/neilstripe/Blockchain-Scalability-Book"
edit-url-template = "https://github.com/neilstripe/Blockchain-Scalability-Book/edit/main/{path}"
print = { enable = true }

[build]
build-dir = "book"

