[book]
authors = ["Blockchain Scalability Book Contributors"]
language = "en"
multilingual = false
src = "."
title = "Blockchain Scalability Book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/neilydhan/Blockchain-Scalability-Book"
edit-url-template = "https://github.com/neilydhan/Blockchain-Scalability-Book/edit/main/{path}"

[output.pdf]
margin-left = 1.5
margin-right = 1.5
margin-top = 1.5
margin-bottom = 1.5
page-break = true
display-header = true
display-footer = true
scale = 1.0